---
environment_variables:
  INVENT_VERSION: "0.0.2-1"
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
builders:
  - docker
docker_context_dir: receiver
docker_name: invent/receiver
docker_tags:
  - "${INVENT_VERSION}"
  - "latest"
docker_no_cache: true
