---
environment_variables:
  INVENT_VERSION: "0.0.1-1"
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
builders:
  - docker
docker_context_dir: reciever
docker_name: invent/reciever
docker_tags:
  - "${INVENT_VERSION}"
  - "latest"
docker_no_cache: true
