clean_workspace: true
docker_no_cache: true
git:
  branch: main
triggers:
  github_push: false
  cron: "@weekly"
extra_jobs:
  - name: invent-reciever
    builders:
      - docker
    docker_context_dir: reciever
    docker_name: invent/reciever
    docker_tags:
      - "latest"
    triggers:
      github_push: true
      cron: "@weekly"
